DROP DATABASE IF EXISTS buscompany;
CREATE DATABASE buscompany;
USE buscompany;

CREATE TABLE `user`(
id INT NOT NULL AUTO_INCREMENT,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
patronymic VARCHAR(50) DEFAULT NULL,
login VARCHAR(50) NOT NULL UNIQUE,
`password` VARCHAR(50) NOT NULL,
user_type ENUM('CLIENT','ADMIN') NOT NULL,
PRIMARY KEY(id)
)
 ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `client` (
id INT NOT NULL,
email VARCHAR(50) NOT NULL,
phone VARCHAR(50) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY(id) REFERENCES `user`(id) ON DELETE CASCADE 
)
 ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;
 
CREATE TABLE `admin` (
id INT NOT NULL,
`position` VARCHAR(50) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id) REFERENCES `user`(id) ON DELETE CASCADE 
)
 ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;
 
 CREATE TABLE `bus`(
 busName VARCHAR(45) NOT NULL,
 placeCount INT NOT NULL,
 PRIMARY KEY(busName)
 )
 ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;
 
 CREATE TABLE `trip`(
 id INT NOT NULL AUTO_INCREMENT,
 busName VARCHAR(45) DEFAULT NULL,
 fromStation VARCHAR(45) NOT NULL,
 toStation VARCHAR(45) NOT NULL,
 `start` TIME NOT NULL,
 duration INT NOT NULL,
 price INT NOT NULL,
 isapproved BOOLEAN DEFAULT FALSE,
 PRIMARY KEY(id),
 FOREIGN KEY(busName) REFERENCES bus(busName) ON DELETE SET NULL
 )
  ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;
 
 CREATE TABLE `schedule`(
 id_trip INT NOT NULL,
 fromDate DATE NOT NULL,
 toDate DATE NOT NULL,
 period VARCHAR(50) NOT NULL,
 PRIMARY KEY(id_trip),
 FOREIGN KEY(id_trip) REFERENCES `trip`(id) ON DELETE CASCADE
 )
 ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;
 
 
 CREATE TABLE `trip_date`(
 id_trip INT NOT NULL,
 `date` DATE NOT NULL,
 free_places INT NOT NULL,
 PRIMARY KEY(id_trip, `date`),
 FOREIGN KEY(id_trip) REFERENCES `trip`(id) ON DELETE CASCADE
 )
 ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `session`(
id VARCHAR(50) NOT NULL,
id_user INT NOT NULL UNIQUE,
last_access_time DATETIME NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(id_user) REFERENCES `user`(id) ON DELETE CASCADE 
 )
  ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;
 
 
CREATE TABLE `order`(
id INT NOT NULL AUTO_INCREMENT,
id_trip INT NOT NULL,
id_client INT NOT NULL,
fromStation VARCHAR(50) NOT NULL,
toStation VARCHAR(50) NOT NULL,
busName VARCHAR(50) DEFAULT NULL,
`date` DATE NOT NULL,
`start` TIME NOT NULL,
duration INT NOT NULL,
price INT NOT NULL,
totalPrice INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (busName) REFERENCES `bus`(busName) ON DELETE SET NULL,
FOREIGN KEY (id_trip) REFERENCES `trip`(id) ON DELETE CASCADE,
FOREIGN KEY (id_client) REFERENCES `client`(id) ON DELETE CASCADE
)
ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;
 
 CREATE TABLE `passenger`(
 id INT NOT NULL AUTO_INCREMENT,
 id_order INT NOT NULL,
 firstName VARCHAR(50) NOT NULL,
 lastName VARCHAR(50) NOT NULL,
 passport VARCHAR(50) NOT NULL,
 PRIMARY KEY (id),
 UNIQUE (id_order, passport),
 FOREIGN KEY (id_order) REFERENCES `order`(id) ON DELETE CASCADE
 )
 ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;
 
 CREATE TABLE `place`(
 id_order INT DEFAULT NULL,
 id_trip INT NOT NULL,
 `date` DATE NOT NULL,
 place INT NOT NULL,
 id_passenger INT DEFAULT NULL,
 UNIQUE (id_order, id_passenger),
 PRIMARY KEY (id_trip, `date`, place),
 FOREIGN KEY (id_trip) REFERENCES `trip_date`(id_trip) ON DELETE CASCADE
 )
 ENGINE=INNODB 
 DEFAULT CHARSET=utf8mb4;
 